Repository ca-cwds/cwds-jobs, pull requests merged in 2019-02, with the labels that each got.

#89 Sear 537 facility name address containing special chars
  build.gradle
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/inject/CwsCmsRsDataAccessModule.java
  jobs-facilities-cws/src/test/resources/fixtures/cwsrs_deleted_facility.json
  jobs-facilities-cws/src/test/resources/fixtures/cwsrs_new_facility.json
  jobs-facilities-cws/src/test/resources/fixtures/cwsrs_updated_facility.json
  jobs-facilities-cws/src/test/resources/fixtures/facilities-initial-load-cwscms.json
  jobs-facilities-lis/src/test/resources/fixtures/facilities-lis.json
Labels: facilities-cws, facilities-lis, minor

#90 perry dependency updated
  build.gradle
Labels: cap-users, minor

#91 COG-1105 Changelog fail tolerance improving - indexing job
  build.gradle
  jobs-audit-events/build.gradle
  jobs-audit-events/config/unix_audit-events-job.yaml
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventChangedDto.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventElasticWriter.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventService.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJob.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobConfiguration.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModule.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModuleBuilder.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditInitialJobModeFinalizer.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/NsAuditEventDao.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/identifier/AuditEventIdentifier.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/identifier/AuditEventIdentifiersService.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/AuditEventIdentifiersServiceProvider.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/AuditEventServiceProvider.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/AuditInitialJobModeFinalizerProvider.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/NsDataAccessModule.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/NsSessionFactory.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/AuditEventTestWriter.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/AuditEventsJobTest.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/AuditEvent.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/CreatedEvent.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/CustomEvent.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/CustomEventTest.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/NewValueSetEvent.java
  jobs-audit-events/src/test/resources/audit-events-test.yaml
  jobs-audit-events/src/test/resources/event1.json
  jobs-audit-events/src/test/resources/event2.json
  jobs-audit-events/src/test/resources/event3.json
  jobs-audit-events/src/test/resources/liquibase/ns_audit_events_incremental_data.xml
  jobs-audit-events/src/test/resources/liquibase/ns_audit_events_initial_data.xml
  jobs-common/build.gradle
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/dao/CustomDao.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticSearchIndexerDao.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/AbstractInjectProvider.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/utils/AssertEntityHelper.java
  jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/AbstractChangedFacilityService.java
  jobs-facilities-common/src/test/java/gov/ca/cwds/jobs/cals/facility/AssertFacilityHelper.java
Labels: audit-events, major

#92 Update Perry dependency
  build.gradle
Labels: cap-users, patch

#93 FIT-415 - Update Licensing Shared Library Component to produce CSV file for Java based projects
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: audit-events, patch

#94 SEAR-563,SEAR-564 connection pool tuning for data sources
  jobs-audit-events/config/unix_audit-events-job.yaml
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventElasticWriter.java
  jobs-audit-events/src/test/resources/audit-events-test.yaml
  jobs-cap-users/config/unix_cap-users-job.yaml
  jobs-cap-users/src/test/resources/cap-users-job-runner-test.yaml
  jobs-cap-users/src/test/resources/cap-users-job-test.yaml
  jobs-common/build.gradle
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/batch/BatchProcessor.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/util/SessionFactoryUtil.java
  jobs-common/src/test/resources/testcases/testcase1/config.yaml
  jobs-common/src/test/resources/testcases/testcase10/config.yaml
  jobs-common/src/test/resources/testcases/testcase11/config.yaml
  jobs-common/src/test/resources/testcases/testcase12/config.yaml
  jobs-common/src/test/resources/testcases/testcase2/config.yaml
  jobs-common/src/test/resources/testcases/testcase3/config.yaml
  jobs-common/src/test/resources/testcases/testcase4/config.yaml
  jobs-common/src/test/resources/testcases/testcase5/config.yaml
  jobs-common/src/test/resources/testcases/testcase6/config.yaml
  jobs-common/src/test/resources/testcases/testcase7/config.yaml
  jobs-common/src/test/resources/testcases/testcase9/config.yaml
  jobs-facilities-cws/config/cws-facility-job.yaml
  jobs-facilities-cws/config/unix_cws_facility-job.yaml
  jobs-facilities-cws/cws_facility_index.bat
  jobs-facilities-cws/src/test/resources/cws-test-facility-job.yaml
  jobs-facilities-cws/src/test/resources/cws-test-facility-jobrunner-test.yaml
  jobs-facilities-cws/unix_cws_facility_index.sh
  jobs-facilities-lis/config/lis-facility-job.yaml
  jobs-facilities-lis/config/unix_lis-facility-job.yaml
  jobs-facilities-lis/src/test/resources/lis-test-facility-job.yaml
  jobs-facilities-lis/src/test/resources/lis-test-facility-jobrunner-test.yaml
Labels: audit-events, patch

#95 SEAR-563 triggering CAP User Jobs release
  build.gradle
Labels: cap-users, major

#96 SEAR-563 triggering CWS/CMS Facilities Job release
  build.gradle
Labels: facilities-cws, major

#97 SEAR-563 triggering LIS Facilities Job release
  build.gradle
Labels: facilities-lis, major
