Repository ca-cwds/cwds-jobs, pull requests merged in 2019-03, with the labels that each got.

#98 SEAR-558 upgraded cals-api dependency
  build.gradle
Labels: facilities-cws, patch

#99 SEAR-558 upgraded cals-api dependency
  build.gradle
Labels: facilities-lis, patch

#100 SEAR-558 Added c3po connection pool dependency for lis facility job
  jobs-facilities-lis/build.gradle
Labels: facilities-lis, patch

#101 SEAR-558 Trigger cws job release
  build.gradle
Labels: facilities-cws, minor

#102 SEAR-558 Trigger lis job release
  build.gradle
Labels: facilities-lis, minor

#103 SEAR-560: Application Withdrawn and Application Denied status not showing
  build.gradle
Labels: facilities-cws, patch

#104 SEAR-560: Trigger CWS Job Release
  build.gradle
Labels: facilities-cws, patch

#106 SEAR-560 fixed floating test fail
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/JobMainTest.java
  jobs-common/src/test/resources/testcases/testcase1/config.yaml
  jobs-common/src/test/resources/testcases/testcase10/config.yaml
  jobs-common/src/test/resources/testcases/testcase11/config.yaml
  jobs-common/src/test/resources/testcases/testcase12/config.yaml
  jobs-common/src/test/resources/testcases/testcase2/config.yaml
  jobs-common/src/test/resources/testcases/testcase3/config.yaml
  jobs-common/src/test/resources/testcases/testcase4/config.yaml
  jobs-common/src/test/resources/testcases/testcase5/config.yaml
  jobs-common/src/test/resources/testcases/testcase6/config.yaml
  jobs-common/src/test/resources/testcases/testcase7/config.yaml
  jobs-common/src/test/resources/testcases/testcase9/config.yaml
Labels: facilities-lis, patch

#105 SEAR-560: Trigger LIS Job Release
  build.gradle
Labels: facilities-lis, patch

#109 SEAR-560: Trigger LIS Job Release
  build.gradle
Labels: facilities-lis, patch

#111 SEAR-560: Application Withdrawn and Application Denied status not showing
  build.gradle
Labels: facilities-cws, patch

#112 SEAR-560: Trigger LIS job
  build.gradle
Labels: facilities-lis, patch

#113 COG-1306 AuditEvents Job to Grab Only UnProcessed Events While Run
  build.gradle
  jobs-audit-events/build.gradle
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJob.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModule.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditInitialJobModeFinalizer.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/NsAuditEventDao.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/identifier/AuditEventIdentifiersService.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/identifier/IncrementalModeAuditEventIdentifiersService.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/identifier/InitialModeAuditEventIdentifiersService.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/IncrementalModeAuditEventIdentifiersServiceProvider.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/InitialModeAuditEventIdentifiersServiceProvider.java
  jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/AuditEventsJobTest.java
  jobs-audit-events/src/test/resources/liquibase/ns_audit_events_incremental_data.xml
  jobs-audit-events/src/test/resources/liquibase/ns_audit_events_initial_data.xml
  jobs-cap-users/build.gradle
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/AbstractInjectProvider.java
Labels: audit-events, minor

#114 SEAR-573 Fixed hanging issue
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModule.java
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/inject/NsDataAccessModule.java
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersJobModule.java
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CwsCmsDataAccessModule.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/DataAccessModule.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/util/SessionFactoryUtil.java
  jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/BaseFacilityJobModule.java
  jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/CalsNsDataAccessModule.java
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/inject/CwsCmsRsDataAccessModule.java
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/inject/CwsFacilityJobModule.java
  jobs-facilities-lis/lis_facility_index.bat
  jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/inject/FasDataAccessModule.java
  jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/inject/LisDataAccessModule.java
  jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/inject/LisFacilityJobModule.java
Labels: audit-events, patch

#116 FIT-500 - Create deployment pipelines for CWDS Jobs with manifest file updates
  jenkinsfile-deploy-preint-int.groovy
Labels: audit-events, patch

#115 fixed db2 connection exception when large amount of changes to do
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/CwsChangedUsersServiceImpl.java
Labels: cap-users, patch

#117 SEAR-573 Fixing hanging job
  build.gradle
Labels: facilities-lis, patch

#118 SEAR-573 Trigger CWS job release
  build.gradle
Labels: facilities-cws, patch

#120 FIXED GIT GLITCH
  jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/CalsnsDataAccessModule.java
Labels: facilities-lis, patch

#121 SEAR-571 Trigger lis job release
  build.gradle
Labels: facilities-lis, patch

#125 SEAR-577 trigger LIS job release
  build.gradle
Labels: facilities-lis, patch
