Repository ca-cwds/cwds-jobs, pull requests merged in 2019-04, with the labels that each got.

#128 SEAR-577 fixed sonar bug
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
Labels: audit-events, patch

#129 SEAR-571 trigger audit job release
  build.gradle
Labels: audit-events, major

#130 SEAR-571 trigger cap users release
  build.gradle
Labels: cap-users, major

#131 SEAR-571 trigger lis job release
  build.gradle
Labels: facilities-lis, major

#132 SEAR-571 trigger cws job release
  build.gradle
Labels: facilities-cws, major

#133 SEAR-571 trigger cws job release - patch version
  build.gradle
Labels: facilities-cws, patch

#134 SEAR-571 trigger cws job release
  build.gradle
Labels: facilities-cws, major

#135 Performance test refactored to incapsulate db transaction
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/PerfTestCwsChangedUsersService.java
Labels: cap-users, patch

#136 SEAR-571 Fixed Cap Users job
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersJobModule.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
  jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/BaseFacilityJobConfiguration.java
  jobs-facilities-cws/src/test/resources/cws-test-facility-jobrunner-test.yaml
  jobs-facilities-lis/src/test/resources/lis-test-facility-jobrunner-test.yaml
Labels: cap-users, patch

#137 SEAR-571 Trigger audit job release
  build.gradle
Labels: audit-events, patch

#138 SEAR-571 Fixed injection when creating elastic writers
  jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventElasticWriter.java
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersWriter.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticWriter.java
  jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/FacilityElasticWriter.java
Labels: cap-users, patch

#139 SEAR-571 Trigger cws release
  build.gradle
Labels: facilities-cws, patch

#140 SEAR-571 Trigger lis release
  build.gradle
Labels: facilities-lis, patch

#142 cwds-jobs: Tag git with release version when issuing Hot Fixes
  Jenkinsfile
  jenkinsfile-build.groovy
Labels: facilities-lis, patch

#143 FIT-482 - cwds-jobs: Tag git with release version when issuing Hot Fixes
  jenkinsfile-build.groovy
Labels: facilities-cws, patch

#145 SEAR-571 Trigger cap users job release
  build.gradle
Labels: cap-users, patch

#146 SEAR-571 Trigger cws facilities job release
  build.gradle
Labels: facilities-cws, patch

#147 SEAR-571 Trigger cws facilities job release
  build.gradle
Labels: facilities-cws, patch

#148 SEAR-571 Trigger lis facilities job release
  build.gradle
Labels: facilities-lis, patch

#149 SEAR-571 Handle case when there no indexes to delete from alias
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
Labels: facilities-cws, patch

#150 SEAR-571 Trigger lis job release
  build.gradle
Labels: facilities-lis, patch

#152 SEAR-571 Trigger audit job release
  build.gradle
Labels: audit-events, patch

#153 SEAR-571 Trigger lis job release
  build.gradle
Labels: facilities-lis, patch

#154 SEAR-571 Trigger audit job release
  build.gradle
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
Labels: audit-events, patch

#155 SEAR-571 Trigger cap users job release
  build.gradle
Labels: cap-users, patch

#156 Jenkins pipeline test trigger.
  build.gradle
  jenkinsfile-build-test.groovy
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#158 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#159 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#160 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#161 Jenkins pipeline test
  jenkinsfile-build-test.groovy
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#162 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#163 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#164 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#165 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#166 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: facilities-cws, facilities-lis, patch

#167 Jenkins pipeline test
  jenkinsfile-build-test.groovy
Labels: facilities-cws, facilities-lis, patch

#168 Jenkins pipeline test
  jenkinsfile-build-test.groovy
Labels: facilities-cws, facilities-lis, patch

#169 FIT-549 Fix the critical and major code smells for Cals-jobs in Sonar cube
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/dto/ChangedUserDto.java
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/job/CapUsersIncrementalUpdatesProcessor.java
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/CwsChangedUsersServiceImpl.java
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/IdmService.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/configuration/JobOptions.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/exception/JobExceptionHandler.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/identifier/ChangedEntityIdentifier.java
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CustomDb2Dialect.java
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CwdsJobsLimitHandler.java
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/QueryConstants.java
Labels: facilities-cws, patch

#170 Fix the critical and major code smells for Cals-jobs in Sonar cube
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/batch/BatchProcessor.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/DataAccessModule.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/timereport/JobTimeReport.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/timereport/JobTimeReportTest.java
Labels: facilities-lis, patch

#172 Fix the critical and major code smells for Cals-jobs in Sonar cube
  jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/entity/UserId.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/DataAccessModule.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/timereport/JobTimeReport.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/timereport/JobTimeReportTest.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/timereport/TimeLeftEstimationProviderTest.java
Labels: facilities-cws, patch

#171 Jenkins pipeline test
  jenkinsfile-build-test.groovy
  jenkinsfile-release-trigger.groovy
Labels: facilities-cws, facilities-lis, patch

#173 Jenkins pipeline test
  jenkinsfile-release-trigger.groovy
Labels: audit-events, cap-users, facilities-cws, facilities-lis, patch

#174 sonar fix
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/exception/JobExceptionHandler.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/savepoint/SavePointContainerService.java
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/QueryConstants.java
Labels: facilities-cws, patch

#175 COG-1391: CWDS-Jobs: Increase test coverage to 70%
  jobs-cap-users/src/test/java/gov/ca/cwds/jobs/cap/users/dto/ChangedUserDtoTest.java
  jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/ElasticUtilsTest.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchServiceTest.java
  jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/XPackUtilsTest.java
Labels: facilities-cws, patch

#178 Jenkins pipeline rename jobs.
  jenkinsfile-build-jobs.groovy
  jenkinsfile-release-trigger.groovy
Labels: facilities-lis, patch

#180 Pipeline test
  build.gradle
Labels: audit-events, cap-users, facilities-cws, facilities-lis, patch

#179 SEAR-597: Hotfix - Implement new schema changes in Integration for LIS database
  build.gradle
Labels: facilities-cws, facilities-lis, patch

#181 Jobs rename.
  jenkinsfile-release-trigger.groovy
Labels: facilities-cws, patch

#182 Trigger Job Release
  build.gradle
Labels: facilities-cws, facilities-lis, patch

#183 Labels test
  jenkinsfile-release-trigger.groovy
Labels: audit-events, cap-users, facilities-cws, facilities-lis, patch

#184 FIT-482 - cwds-jobs: Tag git with release version when issuing Hot Fixes
  jenkinsfile-build.groovy
Labels: facilities-cws, patch

#185 SEAR-471: Facility search email address not showing in cws/cms - Update dependency
  build.gradle
  jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/inject/CwsCmsRsDataAccessModule.java
Labels: facilities-cws, patch
