Repository ca-cwds/cwds-jobs, pull requests merged in 2019-01, with the labels that each got.

#79 COG-1083 Perry dependency updated to support updated user datamodel
  build.gradle
Labels: enhancement, minor

#80 (FIT-375) Modify CWDS Jobs CI Pipeline to support tagging for multiple artifacts
  Jenkinsfile
Labels: facilities-lis, patch

#81 trigger the build
  Jenkinsfile
Labels: facilities-lis, patch

#83 Moved build stage to the top and added toString() for build fix
  Jenkinsfile
Labels: facilities-lis, patch

#84 COG-1097 fixed date format
  jobs-audit-events/src/main/resources/audit.events.mapping.json
Labels: audit-events, patch

#85 SEAR-538: Search fails if special characters
  jobs-facilities-common/src/main/resources/facility.mapping.json
  jobs-facilities-common/src/main/resources/facility.settings.json
Labels: facilities-cws, facilities-lis, patch

#86 Perry version updated to support updated user datamodel
  build.gradle
Labels: cap-users, minor

#88 COG-1182: Perry dependency version is updated
  build.gradle
Labels: cap-users, patch

#87 SEAR-538: renamed analyzer and added it to facility address
  jobs-facilities-common/src/main/resources/facility.mapping.json
  jobs-facilities-common/src/main/resources/facility.settings.json
Labels: facilities-cws, facilities-lis, patch
